//import {newProject, editProject, newTask, editTask} from './DOMfunctions'

// THIS EVENT LISTENER FILE IS NOT WORKING, BUT IT WORKS WHEN I
// PUT THE SAME CODE IN INDEX.JS. WHY IS THIS? SOMETHING TO DO
// WITH WEBPACK? HOW DO I FIX THIS? WHEN I DO NPM RUN BUILD, 
// IT DOESN'T LOOK LIKE THIS FILE IS INCLUDED IN THE BUILD. 


console.log("EVENT LISTENER BIG BIG BIG TEST!");